FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    mlflow \
    psycopg2-binary \
    boto3

# Create directories for mlflow
RUN mkdir -p /mlruns && chown -R 1000:1000 /mlruns

EXPOSE 5001

CMD ["mlflow", "server", "--help"]